#!/bin/bash

frida_version=12.11.6

platform=$(uname -s | tr '[A-Z]' '[a-z]' | sed 's,^darwin$,macos,')
arch=$1
[ -z "$arch" ] && arch=$(uname -m)

cd "$(dirname $0)"

devkit_url="https://github.com/frida/frida/releases/download/$frida_version/frida-core-devkit-$frida_version-$platform-$arch.tar.xz"
devkit_dir="ext/frida-core/$arch"
if [ ! -f "$devkit_dir/libfrida-core.a" ]; then
  echo ""
  echo "***"
  echo "*** Fetching frida-core devkit for $platform-$arch"
  echo "***"
  rm -rf "$devkit_dir"
  mkdir -p "$devkit_dir"
  pushd "$devkit_dir" > /dev/null
  curl "$devkit_url" -fLo devkit.tar.xz || exit $?
  tar Jxf devkit.tar.xz || exit $?
  rm devkit.tar.xz
  popd > /dev/null
fi

if [ ! -f ext/frida-qml/frida-qml.pri ]; then
  echo ""
  echo "***"
  echo "*** Fetching frida-qml"
  echo "***"
  git submodule init
  git submodule update || exit $?
fi

if [ ! -f app/agent.js ]; then
  echo ""
  echo "***"
  echo "*** Building agent"
  echo "***"
  pushd app/agent > /dev/null
  npm install || exit $?
  popd > /dev/null
fi
