#!/bin/sh

builddir=$1
if [ -z "$builddir" ]; then
  echo "Usage: $0 <builddir>" > /dev/stderr
  exit 1
fi

version=$(grep CRYPTOSHARK_VERSION "$builddir/app/config.h" | cut -f2 -d'"')

# TODO: detect once we build Debian packages for other architectures
arch=amd64

output_deb="$builddir/cryptoshark_$version-1_$arch.deb"

depfile=$(mktemp)
for dep in $(ldd "$builddir/app/cryptoshark" | grep -v "linux-vdso" | awk '{ print $1; }'); do
  depname=$(dpkg -S $dep | grep ":$arch:" | head -1 | cut -f1 -d":")
  depver=$(dpkg-query --showformat='${Version}' --show $depname | cut -f1 -d"-")
  echo "$depname (>= $depver)" >> "$depfile"
done
deps=$(cat "$depfile" | sort -u | tr -s "\n" "," | sed -e "s/,/, /g" -e 's/, $//')
rm "$depfile"

pkgroot=$(mktemp -d) || exit 1
install -m755 -d "$pkgroot/usr/bin" -d "$pkgroot/DEBIAN"
make -C "$builddir/app" install INSTALL_ROOT="$pkgroot"
cat << EOF > "$pkgroot/DEBIAN/control"
Package: cryptoshark
Version: $version-1
Section: debug
Priority: optional
Architecture: $arch
Depends: $deps
Maintainer: Ole André Vadla Ravnås <oleavr@frida.re>
Homepage: https://github.com/frida/cryptoshark
Description: Code tracer powered by Frida
EOF

dpkg-deb --root-owner-group --build "$pkgroot" "$output_deb"
result=$?

rm -r "$pkgroot"

exit $result
